#!/bin/bash

# Bootstrap the install script
apt update && apt upgrade -y
apt install ruby -y

# Run install script
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/mfdorst/linode-scripts/master/debian_init)"
