#!/usr/bin/env ruby

require 'io/console'

# Set the hostname
puts "Hostname: "
`hostnamectl set-hostname #{gets}`

# Install zsh
`apt install zsh -y`

## Create a user with sudo priviledges (default shell: zsh)
puts "Username: "
username = gets.chomp

# Check if user already exists
`id -u #{username} &> /dev/null`
unless $?.success?
  # Create user
  `adduser --gecos "" --disabled-password --shell /bin/zsh #{username}`
  # Set password
  puts "Password:"
  password = STDIN.noecho(&:gets).chomp
  `echo -e #{password}\\n#{password} | passwd #{username}`

  # Give user sudo privilege
  puts "Granting sudo privilege to #{username}"
  `usermod -aG sudo #{username}`
end

## Download dotfiles
puts 'Downloading dotfiles from GitHub...'
`su -c "git clone https://github.com/mfdorst/dotfiles /home/#{username}/.dotfiles" - #{username}`

# Install dotfiles
puts 'Installing dotfiles...'
`su -c "/home/#{username}/.dotfiles/install" - #{username}`

puts "Run `dpkg-reconfigure tzdata` to configure your time zone."
