#!/usr/bin/env ruby

require 'io/console'

def user_ask(default, prompt)
  if default != :default_confirm and default != :default_deny
    raise ArgumentError.new("Argument must be either :default_confirm or :default_deny")
  end
  case default
  when :default_confirm
    print "#{prompt} [Y | n] "
    response = gets.chomp.downcase
    not response =~ /n|no/
  when :default_deny
    puts "#{prompt} [y | N] "
    response = gets.chomp.downcase
    not response =~ /y|yes/
  end
end

# Set the hostname
if user_ask :default_confirm, 'Would you like to set the hostname?'
  puts "Hostname: "
  system('hostnamectl set-hostname #{gets}')
end

# Install zsh and rbenv
`command -v zsh`
if $?.success?
  install_zsh = user_ask :default_confirm, 'Would you like to install zsh?'
else
  install_zsh = false
end
`command -v rbenv`
if $?.success?
  install_rbenv = user_ask :default_confirm, 'Would you like to install rbenv?'
else
  install_rbenv = false
end

system('apt install zsh -y') if install_zsh
system('apt install rbenv -y') if install_rbenv

## Create a user with sudo priviledges (default shell: zsh)
if user_ask :default_confirm, 'Would you like to create a new user?'
  puts "Username: "
  username = gets.chomp

  # Check if user already exists
  `id -u #{username}`
  unless $?.success?
    # Create user
    system("adduser --gecos '' --disabled-password --shell /bin/zsh #{username}")
    # Set password
    puts "Password:"
    password = STDIN.noecho(&:gets).chomp
    system("echo -e #{password}\\n#{password} | passwd #{username}")

    # Give user sudo privilege
    puts "Granting sudo privilege to #{username}"
    system("usermod -aG sudo #{username}")
  else
    puts "User #{username} already exists. Skipping..."
  end
  new_user = true
else
  new_user = false
end

if user_ask :default_confirm, 'Would you like to install dotfiles for root?'
  puts 'Donwloading dotfiles from GitHub...'
  system('git clone https://github.com/mfdorst/dotfiles ~/.dotfiles')

  puts 'Installing dotfiles...'
  system('~/.dotfiles/install -y')
end

if new_user and user_ask :default_confirm, "Would you like to install dotfiles for #{username}?"
  puts 'Downloading dotfiles from GitHub...'
  system("su -c 'git clone https://github.com/mfdorst/dotfiles /home/#{username}/.dotfiles' - #{username}")

  puts 'Installing dotfiles...'
  system("su -c '/home/#{username}/.dotfiles/install -y' - #{username}")
end

puts 'Run `dpkg-reconfigure tzdata` to configure your time zone.'
