#!/bin/bash

# Bootstrap the install script
echo "Updating system..."
apt update && apt upgrade -y
if [ command -v ruby &> /dev/null ]; then
    echo "Installing ruby..."
    apt install ruby -y
fi

# Run install script
echo "Running install script..."
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/mfdorst/scripts/master/debian_init)"
