#!/bin/bash

# Symlink certain scripts to /usr/bin
# NOTE: This script relies on the scripts repo directory being located at $HOME/bin

ln -s $HOME/bin/volume-up /usr/bin/volume-up
ln -s $HOME/bin/volume-down /usr/bin/volume-down
ln -s $HOME/bin/setup-displays-conway /usr/bin/setup-displays
ln -s $HOME/bin/setup-sound-conway /usr/bin/setup-sound

