#!/usr/bin/env bash

INSTALL_DIR="$HOME/.local/bin"

mkdir -p $INSTALL_DIR
pushd $INSTALL_DIR
wget -O tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
chmod +x tailwindcss
popd

echo "tailwindcss installed to $INSTALL_DIR"
