#!/bin/bash

if ! command -v pyenv &> /dev/null; then
    echo 'This script relies on pyenv to work.'
    echo "Please install pyenv: 'curl https://pyenv.run | bash'."
    exit 1
fi

pyenv install -l | grep -E '\s+([0-9]+\.){2}[0-9]+$' | tail -n 1 | awk '{$1=$1};1'
