#!/usr/bin/env fish

echo "> pushd $HOME/code/fluvio"
pushd $HOME/code/fluvio
set -l fish_trace 1

make build-cli build_k8_image
and cargo build --bin fluvio-run
and cargo build --bin fluvio
and $HOME/code/fluvio/target/debug/fluvio cluster delete
and RUST_LOG=fluvio=trace $HOME/code/fluvio/target/debug/fluvio cluster start --develop $argv[1..-1]

set -l exit_code $status
set -e fish_trace
echo "> popd"
popd

exit $exit_code

