#!/usr/bin/env bash

dimensions="$(hyprctl -j activewindow | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')"
path="$HOME/screenshots/$(date +%y%m%d-%H%M%S).jpg"

grim -t jpeg -g "$dimensions" "$path"
