#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "Usage: set-bg <wallpaper-path>"
    exit 1
fi

if ! command -v swaybg &> /dev/null; then
    echo "swaybg is not installed."
    exit 1
fi

killall swaybg
swaybg -i "$1" &>/dev/null &
disown %1
