#!/usr/bin/env bash

places=(".cfg" ".nix" "scripts" "knowledge-base" ".password-store")

for place in "${places[@]}"; do
    if [ -d "$HOME/$place" ]; then
        pushd "$HOME/$place" > /dev/null
        echo "Updating remote for ~/$place"
        git remote update
        popd > /dev/null
    fi
done

echo

for place in "${places[@]}"; do
    if [ -d "$HOME/$place" ]; then
        pushd "$HOME/$place" > /dev/null
        if [[ ! -z "$(git status --porcelain)" ]]; then
            echo "Uncommitted changes in ~/$place:"
            git status -s
        fi
        if [[ $(git rev-parse HEAD) != $(git rev-parse @{u}) ]]; then
            branch=$(git rev-parse --abbrev-ref HEAD)
            upstream=$(git rev-parse --abbrev-ref @{u})
            echo "~/$place: $branch is out of sync with $upstream."
        fi
        popd > /dev/null
    fi
done
