#!/usr/bin/env bash

if ! command -v fzf &> /dev/null; then
    echo "fzf is not installed."
    exit 1
fi

if command -v nvim &> /dev/null; then
    editor=nvim
elif command -v vim &> /dev/null; then
    editor=vim
elif command -v vi &> /dev/null; then
    editor=vi
else
    echo "Neither vim nor neovim are installed."
    exit 1
fi

$editor $(fzf)
