#!/usr/bin/env bash

CONFIG="$HOME/.config/waybar/config"
STYLESHEET="$HOME/.config/waybar/style.css"

CONFIG_FILES="$CONFIG $STYLESHEET"

if ! command -v inotifywait &> /dev/null; then
    echo "inotifywait not found, please install it."
    echo "e.g.: sudo pacman -S inotify-tools"
    exit 1
fi

if ! [ -e "$CONFIG" ]; then
    echo "$CONFIG not found"
    exit 1
fi

if ! [ -e "$STYLESHEET" ]; then
    echo "$STYLESHEET not found"
    exit 1
fi

trap "killall waybar" EXIT

while true; do
    waybar &
    inotifywait -e create,modify $CONFIG_FILES
    killall waybar
done
