#!/usr/bin/env bash

if [ $# -ne 2 ]; then
    echo "Usage: wp-hypr <wallpaper-path> <monitor>"
    echo "e.g.: wp-hypr ~/wallpaper/lo-fi/hoodie-racoon.jpg eDP-1"
    exit 1
fi

if ! command -v hyprctl &> /dev/null; then
    echo "hyprland is not installed."
    exit 1
fi
if ! command -v hyprpaper &> /dev/null; then
    echo "hyprpaper is not installed."
    exit 1
fi

WP_PATH="$1"
MONITOR="$2"

hyprctl hyprpaper preload "$WP_PATH"
hyprctl hyprpaper wallpaper "$MONITOR","$WP_PATH"
