#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "Usage: wp-sway <wallpaper-path>"
    exit 1
fi

if ! command -v swaybg &> /dev/null; then
    echo "swaybg is not installed."
    exit 1
fi

swaybg -i "$1" &
